services:
  vaultwarden-backup:
    container_name: vaultwarden-backup
    platform: linux/amd64
    # to use the already existing docker image, uncomment the next line and comment the whole build section below
    # image: francishgr/vaultwarden-backup
    build:
      context: .
      dockerfile: Dockerfile
      args:
        APP_DATA_LOCATION: ${APP_DATA_LOCATION}
    env_file:
      - .env
    volumes: 
      - /root/docker/vaultwarden-backup:${APP_DATA_LOCATION}
    command: bash -c "chmod +x ${APP_DATA_LOCATION}/create_backup.sh && chmod +x ${APP_DATA_LOCATION}/decrypt_backup.sh && tail -f /dev/null"

